### ISSUE TITLE
Disable verbose output for non-interactive runs

### ISSUE THREAD

**Issue by apjanke** [cbeust/kobalt#156]
Could interactive-style progress updates be disabled, via TTY detection or an option?

When running inside a Jenkins job or something similar that collects the output of `kobaltw` in a log file, it looks like download actions still emit frequent progress updates. In an interactive terminal, these do in-place updates, but in a log file they end up filling the log with a lot of repeated progress messages.

We ran in to this when [building kobalt under Mac Homebrew](https://github.com/Homebrew/homebrew/pull/50243). (The Jenkins job is [here](http://bot.brew.sh/job/Homebrew%20Pull%20Requests/43464/), until it ages out of the build history.)

```
==> /usr/local/Cellar/kobalt/0.683/bin/kobaltw assemble
Picked up _JAVA_OPTIONS: -Duser.home=/Library/Caches/Homebrew/java_cache

Downloading https://github.com/cbeust/kobalt/releases/download/0.683/kobalt-0.683.zip 0.0%
Downloading https://github.com/cbeust/kobalt/releases/download/0.683/kobalt-0.683.zip 0.0%
Downloading https://github.com/cbeust/kobalt/releases/download/0.683/kobalt-0.683.zip 0.0%
Downloading https://github.com/cbeust/kobalt/releases/download/0.683/kobalt-0.683.zip 0.0%
Downloading https://github.com/cbeust/kobalt/releases/download/0.683/kobalt-0.683.zip 0.0%
Downloading https://github.com/cbeust/kobalt/releases/download/0.683/kobalt-0.683.zip 0.0%
...
```

Makes reading the logs harder. And for longer processes, these can end up causing truncated logs.

There are also what appear to be some terminal control escape sequences that make it through in the error messages, which can look like garbage when viewed in a context that doesn't support them. For example, the `[31m` and the `[0m` here, which look like leftovers from red-text terminal escapes.

```
Exception in thread "main" [31m*****
***** ERROR java.nio.file.NoSuchFileException: /Library/Caches/Homebrew/java_cache/.kobalt/repository/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.0.0/kotlin-compiler-embeddable-1.0.0.jar.tmp
*****[0m
```

Would it be possible to disable these verbose updates aimed at interactive use, either by checking to see if `stdout` is attached to a TTY (and/or checking the terminal type), or with an explicit command line option?

Slightly related to #135, in that this could be a workaround for situations like that, too.

**Comment by cbeust** [comment]
Good point. This should be fixed with the commit above. I verified this works in my IDEA window but since Travis builds it from source and doesn't download it, I haven't been able to verify the fix there yet.

And I guess Homebrew won't see the fix until I update the formula to 0.685 there as well.

Let me know what you think.

**Comment by AlexCzar** [comment]
Escape sequences are a bit controversial here, our team uses them in logs extensively as many tools support them and it's nice to have rainbows in the logs :)

**Comment by cbeust** [comment]
My rationale behind using them is that I spend so much time staring at this
text that I might as well make it pretty :-)

Still, Kobalt doesn't go overboard with them (and I used to have colors but
ended up turning them off since I work on a variety of terminals all with
different schemes and I was never able to find a set of colors in Kobalt
that works well in all of them).

But I totally agree that these should be turned off when running on non
interactive consoles, and I hope my patch addresses that.

-- 
Cédric

**Comment by cbeust** [comment]
Closing. Please reopen if you're still seeing these characters on non interactive terminals.
