### ISSUE TITLE
File not found: .kobalt/wrapperVersion.txt

### ISSUE THREAD

**Issue by sargunster** [cbeust/kobalt#176]
1) Take a kobalt project
2) Update to 0.747
3) Delete local ".kobalt" folder
4) Run a kobalt task (I did "kobalt test")
5) File not found: .kobalt/wrapperVersion.txt

You can see the exception in the log of this build: https://travis-ci.org/sargunster/KtUnits/builds/125856917. 

This happens in my project http://github.com/sargunster/KtUnits.

**Comment by cbeust** [comment]
This was a bug in the wrapper, thanks!

Note that because of another bug, just updating to the latest might not fix this. If you are still seeing the error, it's because the wrapper jar file was not copied, which you can fix with:

```
cp  ~/.kobalt/wrapper/dist/kobalt-0.749/kobalt/wrapper/kobalt-wrapper.jar kobalt/wrapper
```

Once you have this wrapper, future updates should copy the correct wrapper.
