### ISSUE TITLE
Couldn't resolve nl.komponents.kovenant:kovenant:jar:3.2.2

### ISSUE THREAD

**Issue by sargunster** [cbeust/kobalt#199]
![](https://cloud.githubusercontent.com/assets/1320357/15236943/8f699a52-1897-11e6-977e-f969ead0eeb6.png)

It doesn't resolve Kovenant, but everything builds (and runs) fine anyway. All my other libraries resolve fine.

My repo is here: https://github.com/pokesource/pokekotlin

My build file is here: https://github.com/pokesource/pokekotlin/blob/master/kobalt/src/Build.kt

**Comment by cbeust** [comment]
Indeed. I think Kobalt should not issue a warning here.

This package is just a `.pom` (no artifacts) that points to other packages, and Kobalt is (erroneously) telling you it can't resolve it probably because it can't find a jar file there, but it's perfectly legal for just a `.pom` to be present.

I'll make sure Kobalt doesn't issue a warning in that case.

**Comment by cbeust** [comment]
Fixed in latest.

**Comment by sargunster** [comment]
Still getting the warning on Kobalt 0.779.

**Comment by cbeust** [comment]
Try 0.780.

**Comment by sargunster** [comment]
Yep, works now.
