### ISSUE TITLE
Possibility to exclude Kotlin runtime from fatJar

### ISSUE THREAD

**Issue by DevCharly** [cbeust/kobalt#235]
When using Kotlin and building a **fatJar**, Kobalt automatically includes the Kotlin runtime into the fatJar. This is fine for applications, but not necessary for Kobalt plugin (or libraries).

Who knows what happens when two different Kotlin runtimes are on classpath...

It should be possible to exclude the Kotlin runtime from fatJar.
E.g. with
```
dependencies {
    provided("org.jetbrains.kotlin:kotlin-stdlib:")
}
````

**Comment by cbeust** [comment]
The reason why `provided` is not working here is that Kobalt automatically adds the Kotlin `stdlib` and `runtime` to all Kotlin projects. Since they are never explicitly specified and they don't really have Maven coordinates, `provided` doesn't apply to them.

As such, I think I should probably provide a special case setting where the user can specify they don't want the Kotlin libraries, maybe something like:

```
val p = project {
    includeKotlinStdlib = false
    includeKotlinRuntime = false
```

What do you think?

**Comment by mattibickel** [comment]
I don't think that the language runtime should be an automagic exception for *fatJar*. The same conflicts can arise between an included 3rd party library and the consumer's version.
When I consume a fat jar, I'm basically tied to whatever the jar brings and I don't see why the language runtime version should be an exception.

I haven't tried this, but would the non-fat version bundle the runtime, too? Because that sounds more like an issue. I'd be rather surprised if my libraries come with a runtime when I didn't indicate I wanted a "ready to run" version by giving `fatJar = true`.

**Comment by dmitry-zhuravlev** [comment]
> I haven't tried this, but would the non-fat version bundle the runtime, too? Because that sounds more like an issue. I'd be rather surprised if my libraries come with a runtime when I didn't indicate I wanted a "ready to run" version by giving fatJar = true.

Fully agree with this.

**Comment by dmitry-zhuravlev** [comment]
So this option should be related only to fatJar

**Comment by cbeust** [comment]
Note that the `kotlin-stdlib` and `kotlin-runtime` jar files add up to about 800Kb so I'm not sure it's really worth worrying about...

**Comment by cbeust** [comment]
I have a working fix but given the polish I would need to add to make it clean and my doubts about the usefulness of such a feature, I think I'll just put it in the ice box for now.

The use cases where you have a Kotlin project but you don't want the Kotlin runtime in your fat jar are just too rare.

**Comment by DevCharly** [comment]
Thanks for your efforts.

Found out that Kobalt already supports excluding files from Jars.
There is an undocumented exclude() function...
```
jar {
	fatJar = true

	exclude("**/kotlin-stdlib-*.jar")
	exclude("**/kotlin-runtime-*.jar")
}
```
or for maven
```
mavenJars {
	jar {
		fatJar = true

		exclude("**/kotlin-stdlib-*.jar")
		exclude("**/kotlin-runtime-*.jar")
	}
}
```

**Comment by cbeust** [comment]
Good find, @DevCharly.

FYI, it's kind of documented here:  http://beust.com/kobalt/plug-ins/index.html#assemble

The text mentions that `zip` has `include` and `exclude` and all archive directives (`jar`, `war` and `mavenJars`) inherit `zip`.

**Comment by DevCharly** [comment]
Indeed. Sorry, haven't seen it...
