### ISSUE TITLE
Option to force test task to return error if test classes were not found

### ISSUE THREAD

**Issue by sargunster** [cbeust/kobalt#253]
For some reason Kobalt can't find my test classes (will make separate issue) but my CI build still succeeds. There should be an option in the Build.kt to make the build fail when this happens.

Here's a build log: https://travis-ci.org/PokeAPI/pokekotlin/builds/141799923

**Comment by cbeust** [comment]
Yes I can reproduce the problem. I made a few changes in that area, I broke something. Looking into it.

**Comment by cbeust** [comment]
I'm not sure it's a good idea to break the build if no test classes can be found because it can happen if you have multiple projects and you just invoked `test`. I often do this for Kobalt itself, which has three projects but only the last one has tests. I don't want the build to break because the first two projects don't have tests and I'd like to be able to say just `"kobaltw test"` instead of `"kobaltw kobalt:test"`.

**Comment by sargunster** [comment]
I think it should be an option, so if I set the flag in the Build.kt for a
module then that module's build will fail without tests. Sometimes I have
issues where the tests can't be found, so the test succeeds and I don't
find out about the issue for a while. Maybe add a flag `testsRequired =
true` (with default to false) in the `test` block of the build file?
Alternatively, require >= 1 tests for modules with the `test` block
specified but don't for modules without it.

**Comment by cbeust** [comment]
Agreed, I think breaking if the project has a `test{}` directive but no tests could be found is reasonable.

**Comment by cbeust** [comment]
Interesting development.

I always add a default `TestConfig` on all projects, even those that don't define a `test{}` directive. This is so that you don't have to specify a `test{}` directive just for the tests to kick in.

So we're confronted with a dilemma:

- Either keep things as they are. Pro: tests run automatically even without a `test{}`. Con: you get a warning if you don't have test source files.

- Remove the default `TestConfig`. Pro: no more warnings if you don't have source files. Con: if you want tests to run, you have to define a `test{}` directive.

I think I still prefer the former solution: `test{}` is silly boilerplate in my opinion. And I can convert the warning into a level 2 log so that users will never see it.

**Comment by sargunster** [comment]
Is it possible to tell the difference between a user specified test
directive vs one applied by default?

Otherwise, an option like `{ failIfNoTests=true }` should work.

**Comment by cbeust** [comment]
Let me know what you think of this fix.

**Comment by sargunster** [comment]
Should be good, thanks
