### ISSUE TITLE
ILocalMavenRepoPathInterceptor current issues

### ISSUE THREAD

**Issue by ethauvin** [cbeust/kobalt#289]
After `repoPath`: 

```
Final list of repos:
  https://jcenter.bintray.com/
  http://repo1.maven.org/maven2/
  file://C:\Users\erik\.kobalt\localMavenRepo/ <-- Kobalt
  K:/maven/repository/ <-- via plugin/repoPath
  http://repository.jetbrains.com/all/
```

Issues:
1. `file://C:\Users\erik\.kobalt\localMavenRepo/` should be overridden.
2. `K:/maven/repository/` probably won't work. `repoPath` should expect a `file` URI, or maybe a `path`.

The order of the repos is concerning too. It would make sense that the maven local repo is checked first. One of the reasons to have a local repo is to potentially override other repos.

**Comment by cbeust** [comment]
I fixed the second item. The first one is a bit more tricky and I can only think of a hacky way to fix it right now so I'll leave it open and see if I can think of a cleaner way to fix it (it's not a huge deal in practice since that local maven repo will probably be empty if you decided to use Maven's local repo anyway).

For future reference, this comes from the two pass compilation of the build file: the first pass compiles just the `repos(localMaven())` line and at that time, the interceptor hasn't kicked in yet. Then I compile the whole build file with the plug-ins applied and that file gets run again, with the correct version of `localMaven()` this time, which is why we end up with both the default one and the interceptor one.

**Comment by ethauvin** [comment]
Outdated.
