### ISSUE TITLE
All versions of kobalt-plugin-api are downloaded not just latest

### ISSUE THREAD

**Issue by ethauvin** [cbeust/kobalt#344]
See enclosed Travis [log](https://github.com/cbeust/kobalt/files/846622/log.txt) for https://travis-ci.org/ethauvin/kobalt-maven-local

[Project](https://github.com/ethauvin/kobalt-maven-local) uses:

```
val kobaltDependency = if (dev) "kobalt" else "kobalt-plugin-api"
...
compile("com.beust:$kobaltDependency:")
...

**Comment by cbeust** [comment]
A simple `k --resolve com.beust:kobalt-plugin-api:` reproduces the problem.

This is translated into `"com.beust:kobalt-plugin-api:(0,]"` by Kobalt and then passed to Maven Resolver, so I'm not sure it's a Kobalt bug or even a Maven Resolver bug: maybe it's necessary to download all these `.pom` files in order to select the highest version.

I will see if I can get someone from the Maven Resolver team to answer this,

**Comment by dittert** [comment]
I think it also happens with `./kobaltw --listTemplates`.

**Comment by cbeust** [comment]
I exchanged emails with the Maven Resolver team and they think it's a bug on their part. I need to file an issue at http://maven.apache.org/resolver/issue-tracking.html

Excerpt from my discussions:

> It smells the bug :( AFAIR we don't need to download POMs to resolve ranges, we are supposed to do this from our metadata
In your case from https://jcenter.bintray.com/com/beust/kobalt-plugin-api/:maven-metadata.xml
> I don't see why we should download / read all POMs

**Comment by ethauvin** [comment]
Fixed.
