### ISSUE TITLE
Any use of kobaltw partially initializes current directory

### ISSUE THREAD

**Issue by ruckustboom** [cbeust/kobalt#469]
It appears any use of the `kobaltw` command partially initializes the current directory as a Kobalt project, including `kobaltw --help`.

To test, you can create a directory, go into it and run any kobalt command (e.g. `kobaltw --help` or even just `kobaltw`*). The directory will then be initialized with the following:
- `.kobalt/` directory
- `kobalt/` directory
- `kobaltw` shell script
- `kobaltw.bat` windows batch script

This has been tested on Windows 10 and Fedora 27.

_\*Note that running `kobaltw` in an empty directory will do the partial initialization then crash when it can't find a `Build.kt` file_

**Comment by ethauvin** [comment]
At the very least the behavior is inconsistent. 

Note that `gradle` also create a `.gradle` directory unless `--help`, `--version`, etc. is used.

`kobatlw` has various behaviors, depending on whether the `--` options processing is located in the wrapper, or the app. For example:

```sh
kobaltw --version
```

will only create a `kobalt` directory containing the wrapper's properties.

I'm pretty sure I can make options like `--help` and `--version` create no directories, etc. I'm not entirely convinced that anything else is in need of fixing. @cbeust, thoughts?

As a side note, '--help' does not include `--version`, because `--version` is in the wrapper, not the app. That might need fixing too.

**Comment by cbeust** [comment]
I think nothing should be created if Kobalt can't find a `kobalt/src/Build.kt`.
